# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='wikipedia',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to=b''),
        ),
    ]
