# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 22:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0004_auto_20170621_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='wikipedia',
        ),
        migrations.AddField(
            model_name='company',
            name='nasdaq',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.CharField(max_length=210),
        ),
        migrations.AlterField(
            model_name='user',
            name='django_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
