# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 02:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0005_auto_20170627_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='wikipedia',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companystockvalue',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 2, 23, 17, 38, 276393)),
        ),
    ]
