# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 22:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0006_auto_20170702_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 7, 3, 19, 48, 35, 587527))),
                ('headline_link', models.TextField()),
                ('headline_text', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='siteApp.Company')),
            ],
        ),
        migrations.AlterField(
            model_name='companystockvalue',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 3, 19, 48, 35, 586572)),
        ),
    ]
