# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 02:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0007_auto_20170703_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companynews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 4, 23, 28, 28, 383084)),
        ),
        migrations.AlterField(
            model_name='companystockvalue',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 4, 23, 28, 28, 382065)),
        ),
    ]
