# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 18:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0008_auto_20170704_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companynews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 6, 15, 59, 0, 637361)),
        ),
        migrations.AlterField(
            model_name='companystockvalue',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 6, 15, 59, 0, 636450)),
        ),
    ]
