# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-09 16:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0009_auto_20170709_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='stock',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='companynews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 9, 13, 53, 52, 757142)),
        ),
        migrations.AlterField(
            model_name='companystockvalue',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 9, 13, 53, 52, 756205)),
        ),
    ]
