# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-09 16:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0010_auto_20170709_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companynews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 9, 13, 59, 22, 316717)),
        ),
        migrations.AlterField(
            model_name='companystockvalue',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 9, 13, 59, 22, 315719)),
        ),
    ]
