# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0012_auto_20170709_1359'),
        ('siteApp', '0009_auto_20170706_1559'),
    ]

    operations = [
    ]
