# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 16:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0013_auto_20170713_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companynews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 13, 13, 49, 1, 63674)),
        ),
        migrations.AlterField(
            model_name='companystockvalue',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 13, 13, 49, 1, 62757)),
        ),
    ]
