# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 20:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0013_merge_20170709_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companynews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 9, 17, 48, 55, 557033)),
        ),
        migrations.AlterField(
            model_name='companystockvalue',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 9, 17, 48, 55, 556054)),
        ),
    ]
