# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 00:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0015_auto_20170709_1819'),
        ('siteApp', '0013_auto_20170709_2122'),
    ]

    operations = [
    ]
