# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 05:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0016_merge_20170709_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companynews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 10, 2, 9, 22, 695366)),
        ),
        migrations.AlterField(
            model_name='companystockvalue',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 10, 2, 9, 22, 694416)),
        ),
    ]
